-------------------------------------------------------------------------------
Test set: eu.qped.java.checkers.coverage.CoverageCheckerSystemTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.061 s <<< FAILURE! - in eu.qped.java.checkers.coverage.CoverageCheckerSystemTest
eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_bag  Time elapsed: 0.029 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: TEST 1: JAVA_STR_KT ==> Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_bag(CoverageCheckerSystemTest.java:60)
Caused by: org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.systemTest(CoverageCheckerSystemTest.java:91)
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.lambda$Test_bag$1(CoverageCheckerSystemTest.java:60)
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_bag(CoverageCheckerSystemTest.java:60)

eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_Tutorial_dry_run  Time elapsed: 0.028 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: TEST 1: JAVA_STR_KT ==> Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_Tutorial_dry_run(CoverageCheckerSystemTest.java:42)
Caused by: org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.systemTest(CoverageCheckerSystemTest.java:91)
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.lambda$Test_Tutorial_dry_run$0(CoverageCheckerSystemTest.java:42)
	at eu.qped.java.checkers.coverage.CoverageCheckerSystemTest.Test_Tutorial_dry_run(CoverageCheckerSystemTest.java:42)

